// // Mock data: Products (admin view) (frontend-only)

// import PRODUCT_IMAGES from "./ProductImage";
// export const mockProductsAdmin = [
//   {
//     id: "prd-0001",
//     sku: "WS-OME-0001",
//     name: "Đồng hồ cơ Luxury Pro",
//     categoryId: "cat-mechanical",
//     brandId: "brand-001",
//     price: 12990000,
//     stock: 15,
//     soldQuantity: 24,
//     status: "Hoạt động",
//     image: PRODUCT_IMAGES.luxury,
//     createdAt: "2025-12-10",
//     updatedAt: "2025-12-24",
//   },
//   {
//     id: "prd-0002",
//     sku: "WS-CAS-0002",
//     name: "Đồng hồ thể thao Active",
//     categoryId: "cat-sport",
//     brandId: "brand-003",
//     price: 8990000,
//     stock: 12,
//     soldQuantity: 18,
//     status: "Hoạt động",
//     image: PRODUCT_IMAGES.sport,
//     createdAt: "2025-12-11",
//     updatedAt: "2025-12-25",
//   },
//   {
//     id: "prd-0003",
//     sku: "WS-GAR-0003",
//     name: "Smartwatch Pro Health",
//     categoryId: "cat-smart",
//     brandId: "brand-005",
//     price: 6990000,
//     stock: 9,
//     soldQuantity: 28,
//     status: "Hoạt động",
//     image: PRODUCT_IMAGES.smart,
//     createdAt: "2025-12-12",
//     updatedAt: "2025-12-26",
//   },
//   {
//     id: "prd-0004",
//     sku: "WS-SEI-0004",
//     name: "Đồng hồ Vintage Classic",
//     categoryId: "cat-classic",
//     brandId: "brand-002",
//     price: 7490000,
//     stock: 0,
//     soldQuantity: 12,
//     status: "Ngừng hoạt động",
//     image: PRODUCT_IMAGES.classic,
//     createdAt: "2025-12-13",
//     updatedAt: "2025-12-20",
//   },
//   {
//     id: "prd-0005",
//     sku: "WS-TIS-0005",
//     name: "Đồng hồ cơ Heritage",
//     categoryId: "cat-mechanical",
//     brandId: "brand-004",
//     price: 13990000,
//     stock: 11,
//     soldQuantity: 19,
//     status: "Hoạt động",
//     image: PRODUCT_IMAGES.default,
//      createdAt: "2025-12-14",
//      updatedAt: "2025-12-27",
//   },
//   // Mock thêm sản phẩm cho các kỳ gần nhất (ngày, tháng, năm)
//   {
//     id: "prd-0006",
//     sku: "WS-OME-0006",
//     name: "Đồng hồ cơ mới nhất",
//     categoryId: "cat-mechanical",
//     brandId: "brand-001",
//     price: 15990000,
//     stock: 10,
//     soldQuantity: 5,
//     status: "Hoạt động",
//     image: PRODUCT_IMAGES.luxury,
//     createdAt: "2025-12-29",
//     updatedAt: "2025-12-29",
//   },
// ];

// export default mockProductsAdmin;
