// // Mock data for products
// export const mockProducts = [
//   {
//     id: 1,
//     name: "Đồng hồ cơ Luxury Pro",
//     description: "Đồng hồ cơ cao cấp, thiết kế sang trọng phù hợp cho các dịp quan trọng.",
//     price: 12990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "mechanical",
//     brand: "Omega",
//     stock: 15,
//     soldQuantity: 24,
//     status: "Còn hàng",
//     rating: 4.8,
//     reviews: 24
//   },
//   {
//     id: 2,
//     name: "Đồng hồ thể thao Active",
//     description: "Đồng hồ thể thao bền bỉ, chống nước, phù hợp cho các hoạt động ngoài trời.",
//     price: 8990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "sport",
//     brand: "Casio",
//     stock: 12,
//     soldQuantity: 18,
//     status: "Còn hàng",
//     rating: 4.5,
//     reviews: 18
//   },
//   {
//     id: 3,
//     name: "Smartwatch X5",
//     description: "Đồng hồ thông minh với nhiều tính năng hiện đại, theo dõi sức khỏe và kết nối với điện thoại.",
//     price: 24990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "smart",
//     brand: "Apple",
//     stock: 8,
//     soldQuantity: 56,
//     status: "Còn hàng",
//     rating: 4.9,
//     reviews: 56
//   },
//   {
//     id: 4,
//     name: "Đồng hồ Vintage Classic",
//     description: "Đồng hồ thiết kế cổ điển, mang phong cách vintage nhưng vẫn giữ được nét hiện đại.",
//     price: 7490000,
//     image: "/assets/images/products/watch.jpg",
//     category: "classic",
//     brand: "Seiko",
//     stock: 0,
//     soldQuantity: 12,
//     status: "Hết hàng",
//     rating: 4.6,
//     reviews: 12
//   },
//   {
//     id: 5,
//     name: "Đồng hồ thể thao Pro",
//     description: "Đồng hồ thể thao chuyên nghiệp với GPS và nhiều tính năng thể thao.",
//     price: 15990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "sport",
//     brand: "Garmin",
//     stock: 10,
//     soldQuantity: 32,
//     status: "Còn hàng",
//     rating: 4.7,
//     reviews: 32
//   },
//   {
//     id: 6,
//     name: "Đồng hồ cơ Automatic",
//     description: "Đồng hồ cơ tự động với bộ máy chính xác cao, thiết kế tinh tế.",
//     price: 11990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "mechanical",
//     brand: "Seiko",
//     stock: 14,
//     soldQuantity: 45,
//     status: "Còn hàng",
//     rating: 4.8,
//     reviews: 45
//   },
//   {
//     id: 7,
//     name: "Smartwatch Fit S2",
//     description: "Đồng hồ thông minh gọn nhẹ, theo dõi nhịp tim, giấc ngủ và luyện tập hằng ngày.",
//     price: 3990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "smart",
//     brand: "Xiaomi",
//     stock: 20,
//     soldQuantity: 67,
//     status: "Còn hàng",
//     rating: 4.4,
//     reviews: 67
//   },
//   {
//     id: 8,
//     name: "Đồng hồ Classic Slim",
//     description: "Thiết kế tối giản, mỏng nhẹ, phù hợp đi làm và đi chơi.",
//     price: 4590000,
//     image: "/assets/images/products/watch.jpg",
//     category: "classic",
//     brand: "Daniel Wellington",
//     stock: 16,
//     soldQuantity: 31,
//     status: "Còn hàng",
//     rating: 4.3,
//     reviews: 31
//   },
//   {
//     id: 9,
//     name: "Đồng hồ Sport Runner",
//     description: "Chống nước, bền bỉ, mặt số dễ đọc, phù hợp chạy bộ và hoạt động ngoài trời.",
//     price: 2990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "sport",
//     brand: "Casio",
//     stock: 18,
//     soldQuantity: 22,
//     status: "Còn hàng",
//     rating: 4.2,
//     reviews: 22
//   },
//   {
//     id: 10,
//     name: "Đồng hồ cơ Heritage",
//     description: "Phong cách cổ điển, bộ máy cơ bền bỉ, phù hợp sưu tầm.",
//     price: 13990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "mechanical",
//     brand: "Tissot",
//     stock: 11,
//     soldQuantity: 19,
//     status: "Còn hàng",
//     rating: 4.7,
//     reviews: 19
//   },
//   {
//     id: 11,
//     name: "Smartwatch Pro Health",
//     description: "Theo dõi sức khỏe nâng cao, đo SpO2, thông báo thông minh và pin lâu.",
//     price: 6990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "smart",
//     brand: "Samsung",
//     stock: 9,
//     soldQuantity: 28,
//     status: "Còn hàng",
//     rating: 4.6,
//     reviews: 44
//   },
//   {
//     id: 12,
//     name: "Đồng hồ Vintage Leather",
//     description: "Dây da mềm, mặt kính cổ điển, tạo điểm nhấn lịch lãm.",
//     price: 5290000,
//     image: "/assets/images/products/watch.jpg",
//     category: "classic",
//     brand: "Seiko",
//     stock: 7,
//     soldQuantity: 37,
//     status: "Còn hàng",
//     rating: 4.5,
//     reviews: 16
//   },
//   {
//     id: 13,
//     name: "Đồng hồ Sport Diver",
//     description: "Phong cách lặn biển, chống nước tốt, phù hợp du lịch và thể thao.",
//     price: 9990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "sport",
//     brand: "Citizen",
//     stock: 0,
//     soldQuantity: 58,
//     status: "Hết hàng",
//     rating: 4.6,
//     reviews: 28
//   },
//   {
//     id: 14,
//     name: "Đồng hồ cơ Open Heart",
//     description: "Thiết kế lộ tim, chuyển động ấn tượng, phù hợp tặng quà.",
//     price: 10990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "mechanical",
//     brand: "Orient",
//     stock: 13,
//     soldQuantity: 21,
//     status: "Còn hàng",
//     rating: 4.7,
//     reviews: 37
//   },
//   {
//     id: 15,
//     name: "Smartwatch Kids Safe",
//     description: "Đồng hồ thông minh cho trẻ em, định vị cơ bản, dễ sử dụng.",
//     price: 1990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "smart",
//     brand: "Imoo",
//     stock: 6,
//     soldQuantity: 73,
//     status: "Còn hàng",
//     rating: 4.1,
//     reviews: 58
//   },
//   {
//     id: 16,
//     name: "Đồng hồ Classic Gold",
//     description: "Tông vàng sang trọng, phối đồ dễ, phù hợp các dịp trang trọng.",
//     price: 6490000,
//     image: "/assets/images/products/watch.jpg",
//     category: "classic",
//     brand: "Michael Kors",
//     stock: 10,
//     soldQuantity: 14,
//     status: "Còn hàng",
//     rating: 4.4,
//     reviews: 21
//   },
//   {
//     id: 17,
//     name: "Đồng hồ Sport Tactical",
//     description: "Thiết kế hầm hố, chịu va đập, phù hợp dã ngoại và hoạt động mạnh.",
//     price: 3590000,
//     image: "/assets/images/products/watch.jpg",
//     category: "sport",
//     brand: "G-Shock",
//     stock: 12,
//     soldQuantity: 39,
//     status: "Còn hàng",
//     rating: 4.8,
//     reviews: 73
//   },
//   {
//     id: 18,
//     name: "Đồng hồ cơ Moon Phase",
//     description: "Lịch tuần trăng tinh tế, hoàn thiện đẹp, phù hợp người yêu cơ khí.",
//     price: 18990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "mechanical",
//     brand: "Longines",
//     stock: 8,
//     soldQuantity: 26,
//     status: "Còn hàng",
//     rating: 4.9,
//     reviews: 14
//   },
//   {
//     id: 19,
//     name: "Smartwatch Ultra GPS",
//     description: "GPS đa băng tần, luyện tập chuyên sâu, phù hợp chạy trail và bơi.",
//     price: 9990000,
//     image: "/assets/images/products/watch.jpg",
//     category: "smart",
//     brand: "Garmin",
//     stock: 15,
//     soldQuantity: 44,
//     status: "Còn hàng",
//     rating: 4.7,
//     reviews: 39
//   },
//   {
//     id: 20,
//     name: "Đồng hồ Vintage Roman",
//     description: "Mặt số La Mã cổ điển, thanh lịch, phù hợp phong cách vintage.",
//     price: 5790000,
//     image: "/assets/images/products/watch.jpg",
//     category: "classic",
//     brand: "Fossil",
//     stock: 9,
//     soldQuantity: 16,
//     status: "Còn hàng",
//     rating: 4.3,
//     reviews: 26
//   }
// ];

// export default mockProducts;

